---
apiVersion: v1
kind: Secret
metadata:
  name: shuawest-poi-gateway-app-repo
  namespace: janus-argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/rhdh-gh/shuawest-gateway-gitops
